# Fly.io configuration for SwarmContainer Remote Development
app = "swarmcontainer-dev"  # Will be replaced by actual app name
primary_region = "iad"       # Default to US East, user can change

# Build configuration
[build]
  dockerfile = "Dockerfile"
  target = "remote"

# Environment variables
[env]
  # Public environment variables
  NODE_ENV = "development"
  DEVCONTAINER = "true"
  
  # Memory settings (matching local development)
  CONTAINER_MEMORY = "8g"
  CONTAINER_CPUS = "4"
  
  # Security preset for remote development
  SECURITY_PRESET = "development"

# Process groups
[processes]
  app = "/fly-entrypoint.sh /usr/sbin/sshd -D"

# Services configuration
[[services]]
  # SSH service configuration
  processes = ["app"]
  internal_port = 22
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  # Concurrency settings
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  # Public port mapping
  [[services.ports]]
    port = 10022  # Non-standard SSH port for security

# Persistent storage
[[mounts]]
  # Mount for workspace persistence
  source = "swarm_workspace"
  destination = "/workspace"
  
[[mounts]]
  # Mount for home directory persistence
  source = "swarm_home"
  destination = "/home/node"

# Machine configuration
[experimental]
  # Use Fly Machines v2
  auto_rollback = true

# Health checks
[[services.tcp_checks]]
  interval = "15s"
  timeout = "2s"
  grace_period = "5s"

# Resource allocation
[[vm]]
  # Default to shared CPU for cost efficiency
  cpu_kind = "shared"
  cpus = 2
  memory_mb = 2048